name: sign

on:
  schedule:  # 开启定时需要把这几前面的“#”删掉
    - cron: '30 5 * * *'     #运行的时间，时区问题实际运行+8h
    - cron: '35 5 * * *'
    - cron: '40 5 * * *'
    - cron: '35 9 * * *'
    - cron: '40 9 * * *'
    - cron: '45 9 * * *'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: 'Install dependencies'
        run: |
          pip install httpx
          pip install loguru
          pip install lxml
      - name: 'sign'
        run: python3 sign.py
